name: xtensor-r
channels:
  - conda-forge
dependencies:
  - cmake
  - xtensor=0.24.4
  - r-base
  - r-rcpp
  - m2w64-gcc
  - m2w64-make 
  - m2w64-toolchain
  - m2-libbz2
  - posix
  # test dependencies
  - r-rinside
  - r-devtools
  - r-testthat
