// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/xtensor.h"
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_xtensor
xt::rtensor<double, 2> rcpp_hello_xtensor(xt::rtensor<double, 3> tens);
RcppExport SEXP xtensor_rcpp_hello_xtensor(SEXP tensSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< xt::rtensor<double, 3> >::type tens(tensSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_xtensor(tens));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"xtensor_rcpp_hello_xtensor", (DL_FUNC) &xtensor_rcpp_hello_xtensor, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_xtensor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
